name: AutoDeployHexo

on:
  push:
    branches: 
      - hexo

jobs:
  publish:
    name: Hexo Auto-Deploy by GitHub Actions
    runs-on: ubuntu-latest
    steps:
    - name: 1. git checkout...
      uses: actions/checkout@v1

    - name: 2. setup nodejs...
      uses: actions/setup-node@v1
      with:
        node-version: '10.22.1'
      
    - name: 3. install hexo...
      run: sudo npm install -g hexo-cli
      
    - name: 4. install dependencies...
      run: |
        npm install
        npm install hexo-deployer-git --save

    - name: 5. show hexo version
      run: hexo -v

    - name: 6. clean and generate public files...
      run: hexo clean && hexo g
      
    - name: 7. configure git...
      env:
        GH_TOKEN: ${{secrets.ACTIONS_TOKEN}}
      run: sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
        
    - name: 8. deploy...
      run: sudo hexo d
